import {MigrationInterface, QueryRunner} from "typeorm";

export class probando1592946327792 implements MigrationInterface {
    name = 'probando1592946327792'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `login` DROP FOREIGN KEY `FK_fe26416e4bfa6ae26ab744857a3`");
        await queryRunner.query("ALTER TABLE `login` CHANGE `userIdusuario` `userIdusuario` int NULL");
        await queryRunner.query("ALTER TABLE `unidadproducto` DROP FOREIGN KEY `FK_9cc31fd287491c86a2b987d122c`");
        await queryRunner.query("ALTER TABLE `unidadproducto` CHANGE `productoIdproducto` `productoIdproducto` int NULL");
        await queryRunner.query("ALTER TABLE `imgproducto` DROP FOREIGN KEY `FK_7326f1242701a83701345611aa2`");
        await queryRunner.query("ALTER TABLE `imgproducto` CHANGE `productoIdproducto` `productoIdproducto` int NULL");
        await queryRunner.query("ALTER TABLE `imgcategoria` DROP FOREIGN KEY `FK_ebff784487b8c37b1e25e2b280a`");
        await queryRunner.query("ALTER TABLE `imgcategoria` CHANGE `categoriaIdcategoria` `categoriaIdcategoria` int NULL");
        await queryRunner.query("ALTER TABLE `producto` DROP FOREIGN KEY `FK_549cb47d80500e63cd8029c75d6`");
        await queryRunner.query("ALTER TABLE `producto` CHANGE `precio` `precio` float NOT NULL");
        await queryRunner.query("ALTER TABLE `producto` CHANGE `peso` `peso` float NOT NULL");
        await queryRunner.query("ALTER TABLE `producto` CHANGE `categoriaIdcategoria` `categoriaIdcategoria` int NULL");
        await queryRunner.query("ALTER TABLE `pedidoproducto` DROP FOREIGN KEY `FK_1438cc2588f97093fb7a53f52ff`");
        await queryRunner.query("ALTER TABLE `pedidoproducto` DROP FOREIGN KEY `FK_77362b28d43059b8c2be29d8c34`");
        await queryRunner.query("ALTER TABLE `pedidoproducto` CHANGE `pedidoIdpedido` `pedidoIdpedido` int NULL");
        await queryRunner.query("ALTER TABLE `pedidoproducto` CHANGE `productoIdproducto` `productoIdproducto` int NULL");
        await queryRunner.query("ALTER TABLE `cliente` DROP FOREIGN KEY `FK_112b22b5dd069f8e3b21e9f3e9f`");
        await queryRunner.query("ALTER TABLE `cliente` CHANGE `userIdusuario` `userIdusuario` int NULL");
        await queryRunner.query("ALTER TABLE `repartidor` DROP FOREIGN KEY `FK_bd2b887789203af4bbc788658fd`");
        await queryRunner.query("ALTER TABLE `repartidor` CHANGE `userIdusuario` `userIdusuario` int NULL");
        await queryRunner.query("ALTER TABLE `pedido` DROP FOREIGN KEY `FK_6c0295e2111a86b13f5a2f0c6b0`");
        await queryRunner.query("ALTER TABLE `pedido` DROP FOREIGN KEY `FK_fb87d81237cb737eb19df750e00`");
        await queryRunner.query("ALTER TABLE `pedido` CHANGE `clienteIdcliente` `clienteIdcliente` int NULL");
        await queryRunner.query("ALTER TABLE `pedido` CHANGE `repartidorIdrepartidor` `repartidorIdrepartidor` int NULL");
        await queryRunner.query("ALTER TABLE `venta` DROP FOREIGN KEY `FK_04c211c832d271711c09e3d4198`");
        await queryRunner.query("ALTER TABLE `venta` DROP FOREIGN KEY `FK_115ce5f184fa32c3a00c0a8f61a`");
        await queryRunner.query("ALTER TABLE `venta` CHANGE `total` `total` float NOT NULL");
        await queryRunner.query("ALTER TABLE `venta` CHANGE `vendedorIdvendedor` `vendedorIdvendedor` int NULL");
        await queryRunner.query("ALTER TABLE `venta` CHANGE `pedidoIdpedido` `pedidoIdpedido` int NULL");
        await queryRunner.query("ALTER TABLE `vendedor` DROP FOREIGN KEY `FK_c8bf0c7780bd244d3fb7687f7ed`");
        await queryRunner.query("ALTER TABLE `vendedor` CHANGE `userIdusuario` `userIdusuario` int NULL");
        await queryRunner.query("ALTER TABLE `operacion` DROP FOREIGN KEY `FK_076a263125d1b55dbe49dccb672`");
        await queryRunner.query("ALTER TABLE `operacion` CHANGE `modulosIdmodulo` `modulosIdmodulo` int NULL");
        await queryRunner.query("ALTER TABLE `roloperacion` DROP FOREIGN KEY `FK_d2847a93a71904a31ae4018271d`");
        await queryRunner.query("ALTER TABLE `roloperacion` DROP FOREIGN KEY `FK_2dbb8e17ba9ad37e73a57c91587`");
        await queryRunner.query("ALTER TABLE `roloperacion` CHANGE `operacionsIdoperacion` `operacionsIdoperacion` int NULL");
        await queryRunner.query("ALTER TABLE `roloperacion` CHANGE `rolIdrol` `rolIdrol` int NULL");
        await queryRunner.query("ALTER TABLE `users` DROP FOREIGN KEY `FK_4180b7d401a51680086a1e4f0fe`");
        await queryRunner.query("ALTER TABLE `users` CHANGE `rolIdrol` `rolIdrol` int NULL");
        await queryRunner.query("ALTER TABLE `admin` DROP FOREIGN KEY `FK_7e2d3097b9681a0f1e5827983f6`");
        await queryRunner.query("ALTER TABLE `admin` CHANGE `userIdusuario` `userIdusuario` int NULL");
        await queryRunner.query("ALTER TABLE `login` ADD CONSTRAINT `FK_fe26416e4bfa6ae26ab744857a3` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `unidadproducto` ADD CONSTRAINT `FK_9cc31fd287491c86a2b987d122c` FOREIGN KEY (`productoIdproducto`) REFERENCES `producto`(`idproducto`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `imgproducto` ADD CONSTRAINT `FK_7326f1242701a83701345611aa2` FOREIGN KEY (`productoIdproducto`) REFERENCES `producto`(`idproducto`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `imgcategoria` ADD CONSTRAINT `FK_ebff784487b8c37b1e25e2b280a` FOREIGN KEY (`categoriaIdcategoria`) REFERENCES `categoria`(`idcategoria`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `producto` ADD CONSTRAINT `FK_549cb47d80500e63cd8029c75d6` FOREIGN KEY (`categoriaIdcategoria`) REFERENCES `categoria`(`idcategoria`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `pedidoproducto` ADD CONSTRAINT `FK_1438cc2588f97093fb7a53f52ff` FOREIGN KEY (`pedidoIdpedido`) REFERENCES `pedido`(`idpedido`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `pedidoproducto` ADD CONSTRAINT `FK_77362b28d43059b8c2be29d8c34` FOREIGN KEY (`productoIdproducto`) REFERENCES `producto`(`idproducto`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cliente` ADD CONSTRAINT `FK_112b22b5dd069f8e3b21e9f3e9f` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `repartidor` ADD CONSTRAINT `FK_bd2b887789203af4bbc788658fd` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `pedido` ADD CONSTRAINT `FK_6c0295e2111a86b13f5a2f0c6b0` FOREIGN KEY (`clienteIdcliente`) REFERENCES `cliente`(`idcliente`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `pedido` ADD CONSTRAINT `FK_fb87d81237cb737eb19df750e00` FOREIGN KEY (`repartidorIdrepartidor`) REFERENCES `repartidor`(`idrepartidor`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `venta` ADD CONSTRAINT `FK_04c211c832d271711c09e3d4198` FOREIGN KEY (`vendedorIdvendedor`) REFERENCES `vendedor`(`idvendedor`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `venta` ADD CONSTRAINT `FK_115ce5f184fa32c3a00c0a8f61a` FOREIGN KEY (`pedidoIdpedido`) REFERENCES `pedido`(`idpedido`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `vendedor` ADD CONSTRAINT `FK_c8bf0c7780bd244d3fb7687f7ed` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `operacion` ADD CONSTRAINT `FK_076a263125d1b55dbe49dccb672` FOREIGN KEY (`modulosIdmodulo`) REFERENCES `modulo`(`idmodulo`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `roloperacion` ADD CONSTRAINT `FK_d2847a93a71904a31ae4018271d` FOREIGN KEY (`operacionsIdoperacion`) REFERENCES `operacion`(`idoperacion`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `roloperacion` ADD CONSTRAINT `FK_2dbb8e17ba9ad37e73a57c91587` FOREIGN KEY (`rolIdrol`) REFERENCES `rol`(`idrol`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `users` ADD CONSTRAINT `FK_4180b7d401a51680086a1e4f0fe` FOREIGN KEY (`rolIdrol`) REFERENCES `rol`(`idrol`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `admin` ADD CONSTRAINT `FK_7e2d3097b9681a0f1e5827983f6` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `admin` DROP FOREIGN KEY `FK_7e2d3097b9681a0f1e5827983f6`");
        await queryRunner.query("ALTER TABLE `users` DROP FOREIGN KEY `FK_4180b7d401a51680086a1e4f0fe`");
        await queryRunner.query("ALTER TABLE `roloperacion` DROP FOREIGN KEY `FK_2dbb8e17ba9ad37e73a57c91587`");
        await queryRunner.query("ALTER TABLE `roloperacion` DROP FOREIGN KEY `FK_d2847a93a71904a31ae4018271d`");
        await queryRunner.query("ALTER TABLE `operacion` DROP FOREIGN KEY `FK_076a263125d1b55dbe49dccb672`");
        await queryRunner.query("ALTER TABLE `vendedor` DROP FOREIGN KEY `FK_c8bf0c7780bd244d3fb7687f7ed`");
        await queryRunner.query("ALTER TABLE `venta` DROP FOREIGN KEY `FK_115ce5f184fa32c3a00c0a8f61a`");
        await queryRunner.query("ALTER TABLE `venta` DROP FOREIGN KEY `FK_04c211c832d271711c09e3d4198`");
        await queryRunner.query("ALTER TABLE `pedido` DROP FOREIGN KEY `FK_fb87d81237cb737eb19df750e00`");
        await queryRunner.query("ALTER TABLE `pedido` DROP FOREIGN KEY `FK_6c0295e2111a86b13f5a2f0c6b0`");
        await queryRunner.query("ALTER TABLE `repartidor` DROP FOREIGN KEY `FK_bd2b887789203af4bbc788658fd`");
        await queryRunner.query("ALTER TABLE `cliente` DROP FOREIGN KEY `FK_112b22b5dd069f8e3b21e9f3e9f`");
        await queryRunner.query("ALTER TABLE `pedidoproducto` DROP FOREIGN KEY `FK_77362b28d43059b8c2be29d8c34`");
        await queryRunner.query("ALTER TABLE `pedidoproducto` DROP FOREIGN KEY `FK_1438cc2588f97093fb7a53f52ff`");
        await queryRunner.query("ALTER TABLE `producto` DROP FOREIGN KEY `FK_549cb47d80500e63cd8029c75d6`");
        await queryRunner.query("ALTER TABLE `imgcategoria` DROP FOREIGN KEY `FK_ebff784487b8c37b1e25e2b280a`");
        await queryRunner.query("ALTER TABLE `imgproducto` DROP FOREIGN KEY `FK_7326f1242701a83701345611aa2`");
        await queryRunner.query("ALTER TABLE `unidadproducto` DROP FOREIGN KEY `FK_9cc31fd287491c86a2b987d122c`");
        await queryRunner.query("ALTER TABLE `login` DROP FOREIGN KEY `FK_fe26416e4bfa6ae26ab744857a3`");
        await queryRunner.query("ALTER TABLE `admin` CHANGE `userIdusuario` `userIdusuario` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `admin` ADD CONSTRAINT `FK_7e2d3097b9681a0f1e5827983f6` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `users` CHANGE `rolIdrol` `rolIdrol` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `users` ADD CONSTRAINT `FK_4180b7d401a51680086a1e4f0fe` FOREIGN KEY (`rolIdrol`) REFERENCES `rol`(`idrol`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `roloperacion` CHANGE `rolIdrol` `rolIdrol` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `roloperacion` CHANGE `operacionsIdoperacion` `operacionsIdoperacion` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `roloperacion` ADD CONSTRAINT `FK_2dbb8e17ba9ad37e73a57c91587` FOREIGN KEY (`rolIdrol`) REFERENCES `rol`(`idrol`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `roloperacion` ADD CONSTRAINT `FK_d2847a93a71904a31ae4018271d` FOREIGN KEY (`operacionsIdoperacion`) REFERENCES `operacion`(`idoperacion`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `operacion` CHANGE `modulosIdmodulo` `modulosIdmodulo` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `operacion` ADD CONSTRAINT `FK_076a263125d1b55dbe49dccb672` FOREIGN KEY (`modulosIdmodulo`) REFERENCES `modulo`(`idmodulo`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `vendedor` CHANGE `userIdusuario` `userIdusuario` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `vendedor` ADD CONSTRAINT `FK_c8bf0c7780bd244d3fb7687f7ed` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `venta` CHANGE `pedidoIdpedido` `pedidoIdpedido` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `venta` CHANGE `vendedorIdvendedor` `vendedorIdvendedor` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `venta` CHANGE `total` `total` float(12) NOT NULL");
        await queryRunner.query("ALTER TABLE `venta` ADD CONSTRAINT `FK_115ce5f184fa32c3a00c0a8f61a` FOREIGN KEY (`pedidoIdpedido`) REFERENCES `pedido`(`idpedido`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `venta` ADD CONSTRAINT `FK_04c211c832d271711c09e3d4198` FOREIGN KEY (`vendedorIdvendedor`) REFERENCES `vendedor`(`idvendedor`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `pedido` CHANGE `repartidorIdrepartidor` `repartidorIdrepartidor` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `pedido` CHANGE `clienteIdcliente` `clienteIdcliente` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `pedido` ADD CONSTRAINT `FK_fb87d81237cb737eb19df750e00` FOREIGN KEY (`repartidorIdrepartidor`) REFERENCES `repartidor`(`idrepartidor`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `pedido` ADD CONSTRAINT `FK_6c0295e2111a86b13f5a2f0c6b0` FOREIGN KEY (`clienteIdcliente`) REFERENCES `cliente`(`idcliente`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `repartidor` CHANGE `userIdusuario` `userIdusuario` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `repartidor` ADD CONSTRAINT `FK_bd2b887789203af4bbc788658fd` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `cliente` CHANGE `userIdusuario` `userIdusuario` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `cliente` ADD CONSTRAINT `FK_112b22b5dd069f8e3b21e9f3e9f` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `pedidoproducto` CHANGE `productoIdproducto` `productoIdproducto` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `pedidoproducto` CHANGE `pedidoIdpedido` `pedidoIdpedido` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `pedidoproducto` ADD CONSTRAINT `FK_77362b28d43059b8c2be29d8c34` FOREIGN KEY (`productoIdproducto`) REFERENCES `producto`(`idproducto`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `pedidoproducto` ADD CONSTRAINT `FK_1438cc2588f97093fb7a53f52ff` FOREIGN KEY (`pedidoIdpedido`) REFERENCES `pedido`(`idpedido`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `producto` CHANGE `categoriaIdcategoria` `categoriaIdcategoria` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `producto` CHANGE `peso` `peso` float(12) NOT NULL");
        await queryRunner.query("ALTER TABLE `producto` CHANGE `precio` `precio` float(12) NOT NULL");
        await queryRunner.query("ALTER TABLE `producto` ADD CONSTRAINT `FK_549cb47d80500e63cd8029c75d6` FOREIGN KEY (`categoriaIdcategoria`) REFERENCES `categoria`(`idcategoria`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `imgcategoria` CHANGE `categoriaIdcategoria` `categoriaIdcategoria` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `imgcategoria` ADD CONSTRAINT `FK_ebff784487b8c37b1e25e2b280a` FOREIGN KEY (`categoriaIdcategoria`) REFERENCES `categoria`(`idcategoria`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `imgproducto` CHANGE `productoIdproducto` `productoIdproducto` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `imgproducto` ADD CONSTRAINT `FK_7326f1242701a83701345611aa2` FOREIGN KEY (`productoIdproducto`) REFERENCES `producto`(`idproducto`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `unidadproducto` CHANGE `productoIdproducto` `productoIdproducto` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `unidadproducto` ADD CONSTRAINT `FK_9cc31fd287491c86a2b987d122c` FOREIGN KEY (`productoIdproducto`) REFERENCES `producto`(`idproducto`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `login` CHANGE `userIdusuario` `userIdusuario` int NULL DEFAULT 'NULL'");
        await queryRunner.query("ALTER TABLE `login` ADD CONSTRAINT `FK_fe26416e4bfa6ae26ab744857a3` FOREIGN KEY (`userIdusuario`) REFERENCES `users`(`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

}
